### ISSUE TITLE
Add option to use custom buckets

### ISSUE THREAD

**Issue by RyBo** [stephenhillier/starlette_exporter#11]
It would be nice if we could specify the default buckets for the histogram like this:

```python
buckets = (.5, 1, 3, 5, 10, 15, 20, 30, 45, 60, 80, 100, 125, 150, 175, 200, 250, 300, 400)
app.add_middleware(PrometheusMiddleware, group_paths=True, buckets=buckets)
app.add_route("/metrics", handle_metrics)
```
They provide something similar in the flask_exporter: https://github.com/rycus86/prometheus_flask_exporter/blob/master/prometheus_flask_exporter/__init__.py

Is this something I could put a pull request in for?

**Comment by stephenhillier** [comment]
Great idea. Yes, PRs accepted!
