### ISSUE TITLE
Compared to starlette-prometheus ?

### ISSUE THREAD

**Issue by rgarrigue** [stephenhillier/starlette_exporter#2]
Hi there

I saw that you took inspiration from https://github.com/perdy/starlette-prometheus. How this one is different, why should I use it instead of perdy's ? 

Best regards

**Comment by Lawouach** [comment]
Not the owner of this repo and just a mere user but for me, the licensing makes all the difference here.

**Comment by elrik75** [comment]
I tested both, it seems that starlette-prometheus doesn't export status_code. It's very useful to monitor server or client errors
