### ISSUE TITLE
No info on Python Version

### ISSUE THREAD

**Issue by scotgopal** [stephenhillier/starlette_exporter#25]
Hi there. I would like to contribute to this repo but am unclear on what python version is used for development.

**Comment by stephenhillier** [comment]
The automated tests run on a python 3.7 container so anything prior to that is untested. I just checked and I have also developed and run the tests using 3.9 on my machine. The other test dependencies like starlette (at least 12.9) are in requirements.txt.

**Comment by stephenhillier** [comment]
I just realized Starlette only requires Python 3.6 so I'll probably set up a 3.6 test run for GitHub actions.
