### ISSUE TITLE
Add starlette-exporter into Prometheus documentation

### ISSUE THREAD

**Issue by scotgopal** [stephenhillier/starlette_exporter#28]
Heyya @stephenhillier. Shall we consider adding info about starlette-exporter into the main Prometheus documentation under the [Exporters](https://prometheus.io/docs/instrumenting/exporters/#exporters-and-integrations) section? 

There are many categories there. starlette-exporter would be well placed under the API category with a label 'Starlette/FastAPI exporter'. If it's okay, I can work on this.

**Comment by stephenhillier** [comment]
If you are interested in doing that, that's alright by me.  There aren't many "framework" exporter libraries on the list, I only see the Django exporter under the Third Party Utilities list.  

There are lots of pull requests for adding libraries, see https://github.com/prometheus/docs/pulls?q=is%3Apr+exporter , the comments there might help give an idea of what would need to be provided to have it accepted.
