### ISSUE TITLE
Options to set basename

### ISSUE THREAD

**Issue by rgarrigue** [stephenhillier/starlette_exporter#3]
HI again there

Would you mind adding an option to change the base metric name ? Replacing `starlette_requests_total` by `my_app_requests_total` for example. Because if I keep using this lib, I'll mix up data between differents services

Best regards,

**Comment by stephenhillier** [comment]
Hello, thanks for the suggestion!

There's a new label `app_name` that might help (#1 ). 
```python
app.add_middleware(PrometheusMiddleware, app_name="my_app")
```
You'll be able to filter services using the label: `starlette_requests_total{app_name="my_app"}`

That being said, it probably should be up to you if you want to change the metric name too, so I'll work on implementing this.  Just thought I'd bring the above new label to your attention in case that helps in the meantime.

**Comment by rgarrigue** [comment]
Hi there

I saw the app_name after posting this issue. You're missing a bit of doc in the README.md on the topic by the way.

I'm not sure which one is better to be used with something like Grafana, but implementing this should be quite easy and both options would find their users imho.

**Comment by stephenhillier** [comment]
Thanks, you're right, I'll update the docs! I agree, setting the base name still seems like a good idea to implement.
