### ISSUE TITLE
Custom labels

### ISSUE THREAD

**Issue by PhE** [stephenhillier/starlette_exporter#31]
How to define custom labels that will be used on every starlette_exporter metrics ?
For example to add the user_id (email) extracted from a JWT token or any part of the request/session.

It could be acheive with a callback or by monkey-patching *.

Does it make sense ?

**Comment by intelroman** [comment]
If the data is in headers we can extract specific Key value from header as label.
Example if in header you have:
"JWT": "abc@abc.com"
Then we can get the JWT key as a label.
I'm not sure if is what you wanna but I can take a look in to this.

**Comment by stephenhillier** [comment]
Custom labels now available in 0.14 (#52 )
