### ISSUE TITLE
filter_unhandled_paths  does not work  when root_path is set with fastapi

### ISSUE THREAD

**Issue by Bear1110** [stephenhillier/starlette_exporter#38]
Our team have a common ingress called  `https://base.ingess/`
And my service is named as  `my-service`,  `https://base.ingess/my-service`

I need my openapi.json work normally
So, I set the option for fastapi
```
app = FastAPI(root_path="/my-service")
```
For this, I can let openapi work normally.

However, I turn on the option **filter_unhandled_paths**.

I found that there is no any metrics in `https://base.ingess/my-service/metrics` .
After printed some log for matches method in `usr/local/lib/python3.10/site-packages/starlette/routing.py`. (`print(scope["path"], self.path_regex)`
```
...
/my-service/some-endpoint/ re.compile('^/some-endpoint$')
...
```
This let the result is mismatching.
Someone have a solution or fix for it?

All I think can let it work is replace

`"path": scope.get("root_path", "") + scope.get("path"),`

with

`"path": scope.get("path"),`
at line 171 in `starlette_exporter/middleware.py`

**Comment by Bear1110** [comment]
Update:
Add `root_path_in_servers=False`
```
app = FastAPI(root_path="my-service",root_path_in_servers=False)
```
Both openapi and filter_unhandled_paths  work normally.

Maybe can add some comment in document?

**Comment by stephenhillier** [comment]
Thanks for the report!  If I remember correctly,`scope.get("root_path")` on line 171 was necessary to support routes added with `Mount()`.  It looks like we also need to handle the case where `FastAPI(root_path="...")` is used.

**Comment by Bear1110** [comment]
After I copy your change in pull request, it works! Awesome !!
Thank you.

After you deployed to pypi, I will use it !
