### ISSUE TITLE
docker host problem

### ISSUE THREAD

**Issue by kevinye-2017** [stephenhillier/starlette_exporter#40]
I push code in docker.
I got errors return when I curl localhost:8000/metrics from the outside docker
logs output: 
        curl: (52) Empty reply from server

Inside docker to excute curl command that It can show metrics nomally

**Comment by stephenhillier** [comment]
How are you running the app inside the container (e.g. Uvicorn)? Can you confirm host is set to 0.0.0.0? Do you get a successful response from other endpoints?

**Comment by stephenhillier** [comment]
I assume you've found a solution; please re-open if still having an issue.  :+1:
