### ISSUE TITLE
Support for Queued Requests?

### ISSUE THREAD

**Issue by CodeOnCoffee** [stephenhillier/starlette_exporter#42]
Does starlette_requests_in_progress include requests being held in the request pool?

**Comment by stephenhillier** [comment]
`starlette_requests_in_progress` only tracks requests that Starlette/FastAPI is actively handling.  Requests that are queued in Uvicorn will not be included in the gauge until they are passed to Starlette.  Is that what you mean by request pool?

**Comment by CodeOnCoffee** [comment]
Thanks @stephenhillier . Yes we're trying to get a hold of the number of requests in the queue. Seems like they're held in a ThreadPoolExecutor. I'll keep looking. Perhaps Gunicorn is tracking the in-flight requests and queue.

**Comment by intelroman** [comment]
@CodeOnCoffee 
In gunicorn it look like is called backlog.
Maybe that can be tracked

**Comment by stephenhillier** [comment]
Closing this issue- please reopen if needed.  If you've found a fix or workaround that you can share feel free to post it here if it might be helpful for the README.
