### ISSUE TITLE
Better naming 

### ISSUE THREAD

**Issue by intelroman** [stephenhillier/starlette_exporter#44]
Waiting proposal for naming .. on optional_metrics
Now we have 2 optional metrics 
request_response_body_size => how much bytes the server send back to the client.
client_receive_body_size =>  how much data receive server from client (post/put)

It will be great to have a better naming .

**Comment by stephenhillier** [comment]
What do you think about `response_body_bytes` and `request_body_bytes`?

**Comment by intelroman** [comment]
Yes this make sense.
I will update the naming.
Thank you Stephen.

**Comment by stephenhillier** [comment]
thanks @intelroman! merged your changes in #43
