### ISSUE TITLE
Blocking Calls when in Multiprocess mode

### ISSUE THREAD

**Issue by jgould22** [stephenhillier/starlette_exporter#47]
I am still getting a bit of a handle on how python async works however I have a question.

Since `starlette_exporter` depends on the `client_python` which is not generally async am I blocking the event loop when I enable `client_python`'s multi-process mode?

I can see it uses the file system [here](https://github.com/prometheus/client_python/blob/5c18edef66fd6275550a3da6aa55b6ef1da886fb/prometheus_client/mmap_dict.py#L82) to store/share its metrics between workers and in doing so makes regular file open calls.

Do these open calls block the event loop?

**Comment by stephenhillier** [comment]
I'm not sure I have the Python async chops to be able to answer your question, but if you dig deeper and find any answers please report back. :+1: 

For what it's worth I currently use FastAPI with uvicorn with only one worker, but deployed to a number of pods so I'm not as familiar with multiprocess mode (the deployment config described here: https://fastapi.tiangolo.com/id/deployment/docker/#replication-number-of-processes).

**Comment by stephenhillier** [comment]
Doing some cleanup of older issues. If this is still an issue it may be a good question for the client_python repo. Cheers
