### ISSUE TITLE
status_code displays enum name in stats

### ISSUE THREAD

**Issue by jgould22** [stephenhillier/starlette_exporter#48]
When using code like the example below (with fastapi in this case)
```python
from starlette_exporter import PrometheusMiddleware, handle_metrics
from http import HTTPStatus
from fastapi import FastAPI, HTTPException, Response
import uvicorn

app = FastAPI()
app.add_middleware(PrometheusMiddleware)
app.add_route("/metrics", handle_metrics)


@app.get("/")
async def root():
    return Response(status_code=HTTPStatus.OK)


@app.get("/200")
async def root():
    return {"I am returning 200"}


@app.get("/500")
async def root():
    raise HTTPException(status_code=500)
    return {"I am returning 200"}


@app.get("/500v2")
async def root():
    raise HTTPException(status_code=HTTPStatus.INTERNAL_SERVER_ERROR)
    return {"I am returning 200"}


if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=5000, log_level="info")

```
The status code that is displayed in the metrics is the enum name, not the numeric code.

```
starlette_request_duration_seconds_bucket{app_name="starlette",le="10.0",method="GET",path="/",status_code="HTTPStatus.OK"} 2.0
```

Is this desired behaviour?

Perhaps it might be better to attempt to convert the status code to an int?

I think all we would have to do is maybe do a type check and convert to int right here
https://github.com/stephenhillier/starlette_exporter/blob/master/starlette_exporter/middleware.py#L174

**Comment by stephenhillier** [comment]
Thanks for opening an issue!  No, this was not intended. Unfortunately if anyone else is using HTTPStatus from the http library, they may have already set up their metrics to work with strings like `HTTPStatus.OK` so any changes could break things for them.

The only way I can think of to change this would be to add an option like `always_use_int_status` (naming suggestions welcome), and if that is set to true, always convert to int as you suggested.  Any thoughts?

**Comment by jgould22** [comment]
`always_use_int_status` seems entirely reasonable to me.

**Comment by stephenhillier** [comment]
That looks good to me. Unfortunately I am away during the week-  I can put
up a new release on the weekend. There are some other features I have been
meaning to get out too.

**Comment by jgould22** [comment]
No problem, I will put it in a pull request and you can get to it when you get to it.

**Comment by jgould22** [comment]
Fixed in https://github.com/stephenhillier/starlette_exporter/pull/49
