### ISSUE TITLE
multiprocess using the wrong registry

### ISSUE THREAD

**Issue by GLeurquin** [stephenhillier/starlette_exporter#5]
Hi, I believe that when using prometheus_multiproc_dir, the results are not generated correctly because it uses the wrong registry.

in your __init__.py:
return Response(generate_latest(), status_code=200, headers=headers)
should be 
return Response(generate_latest(**registry**), status_code=200, headers=headers)

otherwise the generated metrics use the default registry, and not the multiprocess one, ending up in metrics being generated per process, and not accumulated for the whole app.

**Comment by stephenhillier** [comment]
Thanks! I implemented the fix you suggested in a9bda183ee9cce659dd5b7f7905117a20ab768a0 and released a new version (v0.4.0)
