### ISSUE TITLE
Library missing py.typed marker

### ISSUE THREAD

**Issue by poofeg** [stephenhillier/starlette_exporter#54]
mypy error:

```
error: Skipping analyzing "starlette_exporter": module is installed, but missing library stubs or py.typed marker
```

* starlette-exporter = "0.14.0"
* mypy = "0.971"
* python = "3.10"

**Comment by stephenhillier** [comment]
Thanks for reporting.  I'm interested in adding type checker support but it will probably take a few weeks before I can look at it (PR welcome).

Are you able to work around it in the meantime with `--ignore-missing-imports` (https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports)?
