### ISSUE TITLE
feature : support open metrics exemplars

### ISSUE THREAD

**Issue by camerondavison** [stephenhillier/starlette_exporter#57]
https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#exemplars-1

https://github.com/prometheus/client_python/blob/f17a8361ad3ed5bc47f193ac03b00911120a8d81/README.md#exemplars

Would it be reasonable to have optional dependencies on open telemetry to get the trace info for a bucket?

**Comment by stephenhillier** [comment]
Yes, that sounds reasonable, and I’m definitely interested in this feature.

**Comment by camerondavison** [comment]
I just read that

> Exemplars are not supported
For multi process mode. That is a bummer. I wonder how much work it would be to fix the prom client.

**Comment by camerondavison** [comment]
https://github.com/prometheus/client_python/issues/826

**Comment by stephenhillier** [comment]
That's too bad, would that be a deal breaker for you?  I might work on adding support for exemplars in single process mode anyway (unless you already wanted to submit a PR)

**Comment by camerondavison** [comment]
I don't have a pr yet. It would be a deal breaker for me. But if you add support I assume it will work when they add the support

**Comment by stephenhillier** [comment]
Added in #58 - unfortunately prometheus_client seems to still not support exemplars for multiprocess mode.  Closing as done since exemplars were added here and it should work for anyone not using multiprocess mode.  Hopefully support is added soon.
