### ISSUE TITLE
Mount has no attribute endpoint

### ISSUE THREAD

**Issue by marco-neumann-jdas** [stephenhillier/starlette_exporter#6]
If you are using starlette `Mount`s (e.g. via FastAPI `StaticFiles`):

```python
app.mount("/static", StaticFiles(directory="some/local/path"), name="static")
```
`starlette_exporter` results in the following error log:

```text
ERROR:    'Mount' object has no attribute 'endpoint'
```

due to this code:

https://github.com/stephenhillier/starlette_exporter/blob/a9bda183ee9cce659dd5b7f7905117a20ab768a0/starlette_exporter/middleware.py#L54-L57

**Comment by stephenhillier** [comment]
Hi, thanks for the report.

The `Mount` object from Starlette doesn't seem to have an `endpoint` attribute, which is what I was using to organize paths for the group_paths option.  That might make it difficult to group metrics for static files under one path (is that the behavior you want?). 

In the meantime I can try to improve the error handling.

**Comment by stephenhillier** [comment]
I have a potential solution that still allows grouping of static file metrics, but it needs more thorough testing... I opened a pull request in case you have any comments. #7
