### ISSUE TITLE
Consider changing `group_paths` default value to `True`

### ISSUE THREAD

**Issue by janluke** [stephenhillier/starlette_exporter#78]
> group_paths: setting this to True will populate the path label using named parameters (if any) in the router path, e.g. /api/v1/items/{item_id}. This will group requests together by endpoint (regardless of the value of item_id). This option may come with a performance hit for larger routers. **Default is False, which will result in separate metrics for different URLs (e.g., /api/v1/items/42, /api/v1/items/43, etc.).**

This seems like a really bad default. 99% of the times this is not what you want and the consequence is really bad: labels explosion.

**Comment by stephenhillier** [comment]
Hi @janluke, you're right, it is a bad default. This library did not have the `group_paths` option in the original version though, so when it was added, it defaulted to the existing behavior at the time (and it probably would have seemed wrong at the time to add a new feature and make it the default all at once). 

It's probably time to bite the bullet and change the default, but I still want to be mindful of the impact that could have on existing users.  I will add a deprecation notice in the next release, and then change the default in the one after that.

**Comment by stephenhillier** [comment]
Defaults for `group_paths` and `filter_unhandled_paths` changed in v0.18.0
